spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: dkw123654
    url: jdbc:mysql://localhost:3306/graduation?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml